python train.py gap-edp \
--dataset facebook \
--epsilon 4 \
--encoder_layers 2 \
--base_layers 1 \
--head_layers 1 \
--combine cat \
--hops 2 \
--hidden_dim 16 \
--activation selu \
--optimizer adam \
--learning_rate 0.01 \
--repeats 10 \
--batch_norm True \
--epochs 100 \
--batch_size full \
--encoder_epochs 100 $@
