python train.py sage-ndp \
--dataset facebook \
--epsilon 8 \
--base_layers 2 \
--head_layers 1 \
--max_degree 100 \
--hidden_dim 16 \
--activation selu \
--optimizer adam \
--learning_rate 0.01 \
--repeats 10 \
--max_grad_norm 1 \
--epochs 10 \
--batch_size 256 $@
